INSERT INTO boxes ( grade, reading_level, description, contents ) VALUES ('Kindergarten', 'K-1', 'This box is for Kindergarten students reading below grade level','This box contains 2 Level A books, 2 Level B books, 4 comprehension activities, and 4 comprehension assessments '  );
INSERT INTO boxes ( grade, reading_level, description, contents ) VALUES ('Kindergarten', 'K-2', 'This box is for Kindergarten students reading at grade level', 'This box contains 3 Level C books, 1 Level D book, 4 comprehension activities, and 4 comprehension assessments ' );
INSERT INTO boxes ( grade, reading_level, description, contents ) VALUES ('Kindergarten', 'K-3', 'This box is for Kindergarten students reading above grade level','This box contains 3 Level D books, 1 Level E book, 4 comprehension activities, and 4 comprehension assessments ' );

INSERT INTO boxes ( grade, reading_level, description, contents ) VALUES ('First', '1-1', 'This box is for First grade students reading below grade level','This box contains 1 Level A book, 1 Level B book, 1 Level C book, 1 Level D book, 4 comprehension activities, and 4 comprehension assessments '  );
INSERT INTO boxes ( grade, reading_level, description, contents ) VALUES ('First', '1-2', 'This box is for First grade students reading at grade level','This box contains 1 Level E book, 2 Level F books, 1 Level G book, 4 comprehension activities, and 4 comprehension assessments '  );
INSERT INTO boxes ( grade, reading_level, description, contents ) VALUES ('First', '1-3', 'This box is for First grade students reading above grade level',' This box contains 1 Level G book, 1 Level H book, 1 Level I book, 1 Level J Book, 4 comprehension activities, and 4 comprehension assessments '  );

INSERT INTO boxes ( grade, reading_level, description, contents ) VALUES ('Second', '2-1', 'This box is for Second grade students reading below grade level','This box contains 1 Level E book, 1 Level F book, 1 Level G book, 1 Level H book, 4 comprehension activities, and 4 comprehension assessments '  );
INSERT INTO boxes ( grade, reading_level, description, contents ) VALUES ('Second', '2-2', 'This box is for Second grade students reading at grade level','This box contains 1 Level I book, 1 Level J book, 1 Level K book, 1 Level L book, 4 comprehension activities, and 4 comprehension assessments '  );
INSERT INTO boxes ( grade, reading_level, description, contents ) VALUES ('Second', '2-3', 'This box is for Second grade students reading above grade level','This box contains 1 Level L book, 1 Level M book, 1 Level N book, 1 Level O book, 4 comprehension activities, and 4 comprehension assessments '  );

INSERT INTO boxes ( grade, reading_level, description, contents ) VALUES ('Third', '3-1', 'This box is for Third grade students reading below grade level','This box contains 2 Level L books, 2 Level M books, 4 comprehension activities, and 4 comprehension assessments '  );
INSERT INTO boxes ( grade, reading_level, description, contents ) VALUES ('Third', '3-2', 'This box is for Third grade students reading at grade level','This box contains 1 Level N book, 2 Level O books, 1 Level P book, 4 comprehension activities, and 4 comprehension assessments '  );
INSERT INTO boxes ( grade, reading_level, description, contents ) VALUES ('Third', '3-3', 'This box is for Third grade students reading above grade level','This box contains 1 Level P book, 2 Level Q books, 1 Level R book, 4 comprehension activities, and 4 comprehension assessments '  );

INSERT INTO boxes ( grade, reading_level, description, contents ) VALUES ('Fourth', '4-1', 'This box is for Fourth grade students reading below grade level','This box contains 1 Level M book, 2 Level N books, 1 Level O book, 4 comprehension activities, and 4 comprehension assessments '  );
INSERT INTO boxes ( grade, reading_level, description, contents ) VALUES ('Fourth', '4-2', 'This box is for Fourth grade students reading at grade level','This box contains 1 Level P book, 2 Level Q books, 1 Level R book, 4 comprehension activities, and 4 comprehension assessments '  );
INSERT INTO boxes ( grade, reading_level, description, contents ) VALUES ('Fourth', '4-3', 'This box is for Fourth grade students reading above grade level','This box contains 1 Level S book, 2 Level T books, 1 Level U book, 4 comprehension activities, and 4 comprehension assessments '  );

INSERT INTO boxes ( grade, reading_level, description, contents ) VALUES ('Fifth', '5-1', 'This box is for Fifth grade students reading below grade level','This box contains 1 Level Q book, 2 Level R books, 1 Level S book, 4 comprehension activities, and 4 comprehension assessments '  );
INSERT INTO boxes ( grade, reading_level, description, contents ) VALUES ('Fifth', '5-2', 'This box is for Fifth grade students reading at grade level','This box contains 3 Level T books, 1 Level U book, 4 comprehension activities, and 4 comprehension assessments '  );
INSERT INTO boxes ( grade, reading_level, description, contents ) VALUES ('Fifth', '5-3', 'This box is for Fifth grade students reading above grade level','This box contains 1 Level U book, 2 Level V books, 1 Level W book, 4 comprehension activities, and 4 comprehension assessments '  );

INSERT INTO boxes ( grade, reading_level, description, contents ) VALUES ('Sixth', '6-1', 'This box is for Sixth grade students reading below grade level','This box contains 1 Level T book, 2 Level U books, 1 Level V book, 4 comprehension activities, and 4 comprehension assessments '  );
INSERT INTO boxes ( grade, reading_level, description, contents ) VALUES ('Sixth', '6-2', 'This box is for Sixth grade students reading at grade level','This box contains 1 Level W book, 2 Level X books, 1 Level Y book, 4 comprehension activities, and 4 comprehension assessments '  );
INSERT INTO boxes ( grade, reading_level, description, contents ) VALUES ('Sixth', '6-3', 'This box is for Sixth grade students reading above grade level','This box contains 4 Level Z books, 8 comprehension activities, and recommendations for beyond 6th grade reading'  );
